### ISSUE TITLE
How am I supossed to use the pert-chat? 

### ISSUE THREAD

**Issue by jcpiedrahita** [tecs/pert-chart#1]
I have a 32 milestones list of activities with their respestive dependence rutes, I am wondering how can i use the code to make the correct chart?

**Comment by tecs** [comment]
Hi @jcpiedrahita, thanks for the question.

Following the readme, you are supposed to install all dependencies from within the downloaded source using `npm install` and `bower install`.

After that you have two options - either use the source folder as the root directory in a webserver of your choosing, or install one directly inside the project using `npm i http-server` and then run it with `http-server -p 80`.

You can now access the application by pointing your browser to `http://localhost/` (or the address of the server you deployed it to).

Have in mind that this software is pretty alpha - while I try not to break the file format compatibility and provide migrations, the UI is still very much a work in progress.

Thanks for checking out `pert-chart` and feel free to reopen this issue if you need more help.
