### ISSUE TITLE
is this work

### ISSUE THREAD

**Issue by HanaAlhemyari** [tecs/pert-chart#7]
this code not work when i run it from vs i get two button with white screen

**Comment by tecs** [comment]
Hello,

Unfortunately this project has long been abandoned, but I updated its dependencies and setup process to ensure it is compatible with modern browser standards anyway.

You can either follow the updated readme or use these steps to run the project:
```
npm ci
npm run build
npx http-server -c-1 public
```

Once you the application is up and running, open its URL and create a new project by pressing on the `"new"` button and giving it a name.
